sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make
  - docker run -d --name alpine-glibc ldejager/alpine-glibc /bin/sh -c "sleep 60;"

script:
  - docker ps | grep -q alpine-glibc
