sudo: required

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make build
  - docker run -d --name alpine-glibc rwxlabs/alpine-glibc /bin/sh -c "sleep 60;"

script:
  - docker ps | grep -q alpine-glibc
  - make push
  - curl -X POST -d {} https://hooks.microbadger.com/images/rwxlabs/alpine-glibc/EWCm4SD6_OEQf5eM8vYRADHnX7U=
